# Generated by Django 4.1.4 on 2022-12-08 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0004_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_date', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, default=True, max_digits=100)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ManyToManyField(to='products.product')),
            ],
        ),
        migrations.DeleteModel(
            name='Buy',
        ),
        migrations.AlterField(
            model_name='orders',
            name='customerorder',
            field=models.ManyToManyField(to='products.cart'),
        ),
    ]
