# Generated by Django 4.1.4 on 2022-12-11 20:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0008_cart_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_cart',
            field=models.BooleanField(default=True),
        ),
        migrations.RemoveField(
            model_name='cart',
            name='customer',
        ),
        migrations.AddField(
            model_name='cart',
            name='customer',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
